//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IdCalificacion { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdMateria { get; set; }
        public Nullable<int> IdProfesor { get; set; }
        public Nullable<decimal> Calificacion1 { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
